CURSO_MAP = {
    "administra": "Administração",
    "contabilidade": "Contabilidade",
    "marketing": "Marketing",
    "publicidade": "Publicidade",
    "propaganda": "Publicidade e Propaganda",
    "comunicação": "Comunicação",
    "sistema": "Sistemas de Informação",
    "computação": "Ciência da Computação",
    "engenharia": "Engenharia",
    "software": "Engenharia de Software",
    "dados": "Ciência de Dados",
    "programa": "Desenvolvimento de Sistemas",
    "direito": "Direito",
    "psicologia": "Psicologia",
    "pedagogia": "Pedagogia",
    "enfermagem": "Enfermagem",
    "farmácia": "Farmácia",
}
